# -*- coding: utf-8 -*-

# Form implementation generated from reading ui file 'create-task.ui'
#
# Created by: PyQt5 UI code generator 5.15.9
#
# WARNING: Any manual changes made to this file will be lost when pyuic5 is
# run again.  Do not edit this file unless you know what you are doing.


from PyQt5 import QtCore, QtGui, QtWidgets
from views.taskEdit import Ui_TaskEdit
from views.buttonsFrame_edit import Ui_ButtonsFrame_Edit


class Ui_EditTask(QtWidgets.QDialog):

    """
    Dialog for Task edition.
    """

    def __init__(self, text: str | None = None, headerColor: str = "#006CD3"):
        super().__init__()
        self.setupUi(text, headerColor)


    def setupUi(self, text: str, headerColor: str):

        """
        Set up everything is this dialog.
        """

        self.resize(420, 252)
        self.iscanceled = True
        self.isremoved = False
        self.layout: QtWidgets.QVBoxLayout = QtWidgets.QVBoxLayout(self)
        self.layout.setContentsMargins(10, 10, 10, 10)
        self.layout.setSpacing(10)

        self.taskEdit = Ui_TaskEdit(self)
        self.taskEdit.setText(text)
        self.buttonsFrame = Ui_ButtonsFrame_Edit(self)
        self.buttonsFrame.removeButton.clicked.connect(self.remove)
        self.buttonsFrame.chooseColorButton.setColor(headerColor)
        self.buttonsFrame.saveButton.clicked.connect(self.save)

        self.layout.addWidget(self.taskEdit)
        self.layout.addWidget(self.buttonsFrame)

        self.retranslateUi()
        QtCore.QMetaObject.connectSlotsByName(self)


    def retranslateUi(self):
        _translate = QtCore.QCoreApplication.translate
        self.setWindowTitle(_translate("CreateTask", "Create Task"))


    def save(self):

        """
        Save task.
        """

        self.iscanceled = False
        self.close()


    def remove(self):

        """
        Remove task.
        """

        self.iscanceled = False
        self.isremoved = True
        self.close()